version: '3.8'

services:
  app:
    build: .
    container_name: sps_ungasan
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: sps_ungasan_mysql
    restart: always
    environment:
      MYSQL_DATABASE: sps_ungasan
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sps_ungasan
      MYSQL_PASSWORD: sps_ungasan
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sps_ungasan_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
